### ISSUE TITLE
I got a error when gradle adding

### ISSUE THREAD

**Issue by mohdriyas** [saeedsh92/Banner-Slider#2]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

**Comment by saeedsh92** [comment]
plz send me full stacktrace

**Comment by ahmtkocamn** [comment]
add manifest:
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"++
    package="xx">

<application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        tools:node="replace"> ++

**Comment by CookAmir** [comment]
if i added 
tools:node="replace"
the fcm is not working. it says "notregistered" firebase token. why?
