### ISSUE TITLE
Fragment Support

### ISSUE THREAD

**Issue by derqie** [saeedsh92/Banner-Slider#4]
Hi. I came across this lib and it is simply amazing.
One thing though. Wanted to use it on a fragment instead.
Please help.
Thanks!!

**Comment by aradhell** [comment]
any update about fragments ?

**Comment by saeedsh92** [comment]
you can use it on fragment! there is no problem

**Comment by Ventis** [comment]
How? We get a runtime exception that the Context needs to be an instance of AppCompatActivity

**Comment by jahongir9779** [comment]
the same problem? Want to use it in a dialogFragment...please help
