### ISSUE TITLE
Error inflating class ss.com.bannerslider.views.BannerSlider

### ISSUE THREAD

**Issue by iamnubs** [saeedsh92/Banner-Slider#64]
android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class ss.com.bannerslider.views.BannerSlider

**Comment by PhilipChani** [comment]
Use ss.com.bannerslider.Slider Instead, its what works for me

**Comment by saeedsh92** [comment]
as @PhilipChani said, use slider instead. the ReadMe is fixed and updated now
