### ISSUE TITLE
Slider shows zoomed in photos

### ISSUE THREAD

**Issue by saddahussain** [saeedsh92/Banner-Slider#68]
Even after setting height and width to match parent, it zooms and crops the photo.

**Comment by saddahussain** [comment]
Original Photo.

![screenshot_20180524-170115](https://user-images.githubusercontent.com/20544271/40484225-49bf59e4-5f74-11e8-9165-f7382b97ba56.png)

When set to match parent.
![screenshot_20180524-170118](https://user-images.githubusercontent.com/20544271/40484226-49f097c0-5f74-11e8-8373-ae59b998a623.png)

**Comment by saddahussain** [comment]
Nope. Nothing.

**Comment by robmaas** [comment]
Setting the `ScaleType` in your adapter seems to do the trick:

```
@Override
    public void onBindImageSlide(int position, ImageSlideViewHolder imageSlideViewHolder) {
        imageSlideViewHolder.bindImageSlide(_images.get(position).Url);
        imageSlideViewHolder.imageView.setScaleType(ImageView.ScaleType.FIT_CENTER);
    }
```
