### ISSUE TITLE
Slider pic size is very smaller than normal size

### ISSUE THREAD

**Issue by s-ho-hosseini** [saeedsh92/Banner-Slider#71]
hi
Slider pic size in emulator is good but in my cell phone it is very small and not good at all.
My code and adapter is exactly equivalent your sample code but output is'nt good.

thank you for your supprting.

**Comment by saeedsh92** [comment]
in api 17?

**Comment by s-ho-hosseini** [comment]
no in api 24

**Comment by saeedsh92** [comment]
take an screenshot from this situation, i didn't face with this issue
before

**Comment by s-ho-hosseini** [comment]
Thank you,
Problem fixed,
It is because main viewgroup layout width wasnt matchparent, and when it become match parent work correctly in my huawei cellphone.
I dont now thats why not correct in my cellphoone but work correctly in my 4 various api api andoird emulator!
Thank you for your supportting dear saeed.
