### ISSUE TITLE
Images Fit sizes

### ISSUE THREAD

**Issue by jaison043** [saeedsh92/Banner-Slider#9]
Hi is there a option in which we can set the image sizes as fitxy ,fit center etc.My slider is just 150 dp height.Due to this i cant set my images fit inside the available space.

**Comment by saeedsh92** [comment]
hi , yes. the Banner class has scaleType attribute. you can use it's setter

**Comment by somendrameena** [comment]
Hi @chitra-bahadur, any luck with this ?
@saeedsh92 I also don't see scaleType attribute there
